import type { OpportunityInput } from "./opportunity-engine";

export const mockMarketData: OpportunityInput[] = [
  {
    symbol: "TSLA",
  trendScore: 18,
  elliottScore: 15,
  liquidityScore: 14,
  momentumScore: 15,
  candleScore: 10,
  newsScore: 9,
  sectorScore: 9,
  riskScore: 8,

    priceAboveEma10: true,
    priceAboveMa20: true,
    priceAboveMa50: true,
    macdBullish: true,
    rsi: 61,
    volumeRatio: 1.8,
    breakout: true,
  },
  {
    symbol: "NVDA",
  trendScore: 16,
  elliottScore: 12,
  liquidityScore: 13,
  momentumScore: 14,
  candleScore: 8,
  newsScore: 8,
  sectorScore: 9,
  riskScore: 6,

    priceAboveEma10: true,
    priceAboveMa20: true,
    priceAboveMa50: false,
    macdBullish: true,
    rsi: 58,
    volumeRatio: 1.6,
    breakout: false,
  },
  {
    symbol: "AAPL",
  trendScore: 8,
  elliottScore: 5,
  liquidityScore: 8,
  momentumScore: 5,
  candleScore: 4,
  newsScore: 5,
  sectorScore: 6,
  riskScore: 4,

    priceAboveEma10: true,
    priceAboveMa20: false,
    priceAboveMa50: false,
    macdBullish: false,
    rsi: 47,
    volumeRatio: 1.1,
    breakout: false,
  },
];
